name: Dependency Check

on: workflow_call

jobs:
    depencecy-check:
        runs-on: ubuntu-latest

        steps:
            - name: "Code checkout"
              uses: actions/checkout@v7

            - name: "Setup Go"
              uses: actions/setup-go@v5
              with:
                  working-directory: backend
                  go-version: 1.22
                  go-version-file: backend/go.mod
                  cache-dependency-path: backend/go.sum

            - name: "Install govul check"
              run: go install golang.org/x/vuln/cmd/govulncheck@v1.1.4

            - name: "GoVulncheck"
              continue-on-error: true
              working-directory: backend
              run: govulncheck ./... > reports/vunlerbility.txt

            - name: Setup Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: "20"
                  cache: "npm"
                  cache-dependency-path: frontend/package-lock.json

            - name: Install Dependencies
              working-directory: frontend
              run: npm ci

            - name: NPM Audit
              working-directory: frontend
              run: npm audit

            - name: "Upload Artifact"
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: job-reports
                  path: reports/vunlerbility.txt
                  retention-days: 5
