name: DevsecOps

on:
    push:
        branches:
            - master

jobs:
    # Code open shift  left
    code-quality:
        uses: ./.github/workflows/code-quality.yml

    secret-scan:
        uses: ./.github/workflows/secret-scanning.yml

    dependecy-check:
        uses: ./.github/workflows/dependency-check.yml

    docker-scan:
        uses: ./.github/workflows/docker-scan.yml
        secrets: inherit

    docker-scan:
        uses: ./.github/workflows/sonar-scan.yml
        secrets: inherit    
