name: Secret-scanning

on:
    workflow_call:

jobs:
    scan-scret:
        runs-on: ubuntu-latest
        steps:
            - name: "Code checkout"
              uses: actions/checkout@v7

            - name: "Git leaks"
              uses: actions/checkout@v6
              with:
                  fetch-depth: 0
            - name: "Github Scanner"
              uses: gitleaks/gitleaks-action@v3
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
