name: SonarQube Scan

on:
    workflow_call:

jobs:
    sonarqube:
        runs-on: self-hosted

        steps:
            - name: Checkout Code
              uses: actions/checkout@v6

            - name: SonarQube Scan
              uses: SonarSource/sonarqube-scan-action@v8.2.0
              env:
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                  SONAR_HOST_URL: ${{ secrets.SONAR_URL }}
              with:
                  args: >
                      -Dsonar.projectKey=devboard
                      -Dsonar.projectName=devboard
                      -Dsonar.sources=backend,frontend
